# Generated by Django 5.1.2 on 2024-11-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_remove_invoice_total_amount_invoice_client_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='labour_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
