# Generated by Django 5.1.2 on 2024-11-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_invoiceitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='total_price',
            new_name='subtotal',
        ),
    ]
