# Generated by Django 5.1.2 on 2024-11-14 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_invoice_stamped_invoice_alter_invoice_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_file', models.FileField(upload_to='templates/management/scanned_invoices/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.invoice')),
            ],
        ),
    ]
