# Generated by Django 5.1.2 on 2024-11-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_scannedinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannedinvoice',
            name='scanned_file',
            field=models.FileField(upload_to='management/scanned_invoices/'),
        ),
    ]
