# Generated by Django 5.1.2 on 2024-11-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_alter_scannedinvoice_scanned_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannedinvoice',
            name='scanned_file',
            field=models.FileField(upload_to='management/templates/management/scanned_invoices/'),
        ),
    ]
