# Generated by Django 5.1.2 on 2024-11-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_scannedinvoice_scanned_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_text', models.TextField(default='Above information is not an invoice and only an estimate of services/goods described above. Payment will be collected in prior to provision of services/goods described in this quote. Please confirm your acceptance of this quote by signing this document.\n\nSignature       Print Name       Date\n\nThank you for your business!\nShould you have any enquiries concerning this quote, please contact:\nKen 0731 011 954 | Humphrey 0715 679 643')),
                ('invoice_text', models.TextField(default='PAYMENT DETAILS:\nPAYBILL: 522522\nACCOUNT: 5808345\n----------------------------------\nKCB BANK\nACCOUNT: 1295384434\n\nThank you for your business!\nShould you have any enquiries concerning this Invoice, please contact:\nKen 0707 475 681 | Humphrey 0715 679 643')),
            ],
        ),
    ]
