# Generated by Django 5.1.2 on 2024-11-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_scannedinvoice_scanned_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Paid', 'Paid'), ('Overdue', 'Overdue'), ('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid')], default='Draft', max_length=50),
        ),
    ]
