# Generated by Django 5.1.2 on 2024-11-17 11:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_invoice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_text', models.TextField(default='Above information is not an invoice and only an estimate of services/goods described above. Payment will be collected in prior to provision of services/goods described in this quote. Please confirm your acceptance of this quote by signing this document.\n\nSignature       Print Name       Date\n\nThank you for your business!\nShould you have any enquiries concerning this quote, please contact:\nKen 0731 011 954 | Humphrey 0715 679 643')),
                ('invoice_text', models.TextField(default='PAYMENT DETAILS:\nPAYBILL: 522522\nACCOUNT: 5808345\n----------------------------------\nKCB BANK\nACCOUNT: 1295384434\n\nPlease confirm your Receipt of this Invoice by signing this document.\n\nSignature               Print Name                                      Date\n\nThank you for your business!\nShould you have any enquiries concerning this Invoice, please contact:\nKen 0707 475 681 | Humphrey 0715 679 643')),
            ],
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['payment_date']},
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='description',
        ),
        migrations.AddField(
            model_name='receipt',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payer_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Mobile Money', 'Mobile Money'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='management.invoice'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
