# Generated by Django 5.1.2 on 2024-11-16 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_footnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='footnote',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footnotes', to='management.invoice'),
        ),
        migrations.AddField(
            model_name='footnote',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footnotes', to='management.quotation'),
        ),
    ]
