# Generated by Django 5.1.2 on 2024-11-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_footnote_alter_receipt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Partially Paid', 'Partially Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', editable=False, max_length=20),
        ),
    ]
