# Generated by Django 5.1.2 on 2024-11-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_footnote_invoice_footnote_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footnote',
            name='invoice_text',
            field=models.TextField(default='PAYMENT DETAILS:\nPAYBILL: 522522\nACCOUNT: 5808345\n----------------------------------\nKCB BANK\nACCOUNT: 1295384434\n\nPlease confirm your Receipt of this Invoice by signing this document.\n\nSignature               Print Name                                      Date\n\nThank you for your business!\nShould you have any enquiries concerning this Invoice, please contact:\nKen 0707 475 681 | Humphrey 0715 679 643'),
        ),
        migrations.AlterField(
            model_name='footnote',
            name='quotation_text',
            field=models.TextField(default='Above information is not an invoice and only an estimate of services/goods described above. Payment will be collected in prior to provision of services/goods described in this quote. Please confirm your acceptance of this quote by signing this document.\n\nSignature               Print Name                                      Date\n\nThank you for your business!\nShould you have any enquiries concerning this quote, please contact:\nKen 0731 011 954 | Humphrey 0715 679 643'),
        ),
    ]
