# Generated by Django 5.1.2 on 2024-11-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_receipt_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Partially Paid', 'Partially Paid')], default='Unpaid', editable=False, max_length=20),
        ),
    ]
