# Generated by Django 5.1.2 on 2024-11-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_alter_footnote_invoice_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footnote',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='footnote',
            name='quotation',
        ),
    ]
